"use client";

import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from '@clerk/nextjs';
import { CartContext } from "./_context/CartContext";
import { useState } from "react";
const roboto = Roboto({ subsets: ["latin"], weight: "700" });
// Strapi api key
// 79eb60d9cbe76883bd8ed1a914658bc6b491ac8ff8141fba81081761d35e9bc3e50c59dfcf867a9b166992d21528f0e27a39585f1e1af00d00a88a2d5a961889f896d262fc021ae061b753bfccf4d6c68a72a64e8f234b39c59c7a9d0e1f4bacebd806b5b2d3c13388160c2f37a9b781a6ba223a39040f481ac6d3a9816e24a1
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={roboto.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
